name: Android CI

on:
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup APK signing
      run: |
        echo -n ${{ secrets.SIGNING_KEY }} | base64 -d > app/storeFile.jsk
        echo storeFile=storeFile.jsk > custom.properties
        echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> custom.properties
        echo keyAlias=${{ secrets.ALIAS }} >> custom.properties
        echo keyPassword=${{ secrets.KEY_PASSWORD }} >> custom.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease -PlocalPropertiesFilePath=custom.properties --stacktrace

    - name: Create Release
      uses: actions/upload-artifact@v2
      with:
        name: PCompiler
        path: ./**/*.apk

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: PCompiler
